---
image: docker:///cloudfoundry/diego-ci

paths:
  runtime-metrics-server: gopath/src/github.com/cloudfoundry-incubator/runtime-metrics-server

run:
  path: gopath/src/github.com/cloudfoundry-incubator/runtime-metrics-server/scripts/concourse-test
